# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20160601_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='alias',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('page', 'Page')], default='article', max_length=255),
        ),
    ]
