# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menulink_weight'),
        ('entries', '0003_auto_20160601_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuLink'),
        ),
    ]
