# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='alias',
        ),
    ]
