# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_menulink_entry'),
        ('entries', '0006_remove_entry_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='menu.MenuLink'),
        ),
    ]
