# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20160602_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='entry', to='menu.MenuLink'),
        ),
    ]
