# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
