# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='menu.Menu'),
        ),
    ]
