# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20160601_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulink',
            name='menu',
        ),
        migrations.AddField(
            model_name='menulink',
            name='menu',
            field=models.ManyToManyField(default=1, related_name='links', to='menu.Menu'),
        ),
    ]
