# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20160601_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
