# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_menulink_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='menu',
            field=models.ManyToManyField(null=True, related_name='links', to='menu.Menu'),
        ),
    ]
