# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20160601_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='links', to='menu.Menu'),
        ),
    ]
