# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_remove_entry_link'),
        ('menu', '0011_menulink_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='entries.Entry'),
        ),
    ]
