# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menulink_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulink',
            name='entry',
        ),
    ]
