# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='cid',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='pid',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='val',
            new_name='value',
        ),
    ]
