# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160607_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='columns',
            field=models.ManyToManyField(to='store.Column'),
        ),
    ]
