# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'price',
            },
        ),
        migrations.CreateModel(
            name='TitleColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'title',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='columns',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.PriceColumn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.TitleColumn'),
            preserve_default=False,
        ),
    ]
