# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160607_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecolumn',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('decimal', 'Decimal'), ('text', 'Text')], default='string', max_length=255),
        ),
        migrations.AddField(
            model_name='titlecolumn',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('decimal', 'Decimal'), ('text', 'Text')], default='string', max_length=255),
        ),
    ]
