# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20160607_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlecolumn',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
